# TODO:

# postgres
# temporal
# nexus

#> docker-compose -f docker-compose-kafka2.yml up -d
#> docker-compose -f docker-compose.yml up -d
# wget -U "Any User Agent" https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.0/hadoop-aws-3.3.0.jar
# wget -U "Any User Agent" https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.563/aws-java-sdk-bundle-1.11.563.jar

# chrome:
# http://localhost:8080/namespaces/default/workflows?query=&search=basic
# http://localhost:9001/buckets/default/browse/dGVzdC5jc3Y=
# http://localhost:5010/#browse/browse

version: '3'

services:

  # S3 #
  s3-minio:
    image: "minio/minio"
    environment:
      MINIO_ROOT_USER: "test"
      MINIO_ROOT_PASSWORD: "TeSt1234"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3:/data
    command: "server --console-address :9001 /data"
    networks:
      inner:
        ipv4_address: 172.50.0.30

  # SPARK #
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      inner:
        ipv4_address: 172.50.0.50

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
    networks:
      inner:
        ipv4_address: 172.50.0.61
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
  #        reservations:
  #          cpus: "1"
  #          memory: "1024M"

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
    networks:
      inner:
        ipv4_address: 172.50.0.62
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"

  # NEXUS #
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "5010:8081"
    networks:
      inner:
        ipv4_address: 172.50.0.80
    volumes:
      - nexus-data:/nexus-data
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
# user: admin
# password: > docker exec -it nexus cat /nexus-data/admin.password
# password: f32d7bc6-bc7d-4437-b6de-5ef1c0e4e7e0 > @Dm1n001

volumes:
  s3:
  db:
  nexus-data:

networks:
  inner:
    ipam:
      config:
        - subnet: 172.50.0.0/24


