micronaut:
  application:
    name: scheduler
  server:
    port: 9610

datasources:
  default:
    url: jdbc:postgresql://localhost:55100/example
    driverClassName: org.postgresql.Driver
    username: postgres
    password: test001
    schema-generate: CREATE_DROP
#    schema-generate: CREATE # CREATE_DROP
    dialect: POSTGRES
    schema: demo
#    schema: demo-scheduler

#jpa.default.properties.hibernate.hbm2ddl.auto: update

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
#          auto: validate
        show_sql: true
