version: "3"
name: "etl-tests"
services:
  # DATABASE #
  db:
    image: postgres
    container_name: db-scheduler-test
    restart: always
    environment:
      POSTGRES_PASSWORD: test001
    ports:
      - 55100:5432
#    deploy:
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: "128M"
